# tensorflow = 2.6.0
# python = 3.9.6
# Django = 3.2.8
dependencies:
  - pillow
  - moviepy
  - jupyter
  - pip:
      - ipykernel
      - opencv-python
      - moviepy
      - boto3
      - awscli
      - django